export const ui = '/ui/'
export const api = 'https://localhost/api/'
export const user = 'https://localhost/user'
export const userUpdate = 'https://localhost/user/update'
export const login = 'https://localhost/login'
export const logout = 'https://localhost/logout'
// export const ui = '/ui/'
// export const api = '/api/'
// export const user = '/user'
// export const userUpdate = '/user/update'
// export const login = '/login'
// export const logout = '/logout'
export const statusUnauthorized = 401
export const statusForbidden = 403
export const statusNotFound = 404
